name: 'Workflow: Manual Approval'
description: 'This action allows manual approval of a workflow by commenting "yes" or "no" on an issue.'
author: 'Thomas Joseph'

inputs:
  GITHUB_TOKEN:
    description: "GitHub token for API authentication."
    required: true
    default: ${{ github.token }}
  INPUT_TITLE:
    description: "Title of the issue."
    required: true
    default: "Manual Approval for the Workflow"
  INPUT_BODY:
    description: "Body content of the issue."
    required: false
    default: |
      Provide your approval:
      - Comment "yes" to approve.
      - Comment "no" to reject.
  INPUT_LABELS:
    description: "Comma-separated list of labels for the issue."
    required: false
    default: "yes,no"
  INPUT_ASSIGNEES:
    description: "Comma-separated list of assignees for the issue."
    required: false
    default: ""
  INPUT_TIMEOUT:
    description: "Timeout duration in minutes for the approval process."
    required: false
    default: "30"
  INPUT_MIN_APPROVERS:
    description: "Minimum number of approvals required."
    required: false
    default: "1"

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    INPUT_TITLE: ${{ inputs.INPUT_TITLE }}
    INPUT_BODY: ${{ inputs.INPUT_BODY }}
    INPUT_LABELS: ${{ inputs.INPUT_LABELS }}
    INPUT_ASSIGNEES: ${{ inputs.INPUT_ASSIGNEES }}
    INPUT_TIMEOUT: ${{ inputs.INPUT_TIMEOUT }}

branding:
  icon: 'activity'
  color: 'green'